# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab1/lab1.xdc

# Block Designs: bd/mb_lab1/mb_lab1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1 || ORIG_REF_NAME==mb_lab1} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_microblaze_0_0/mb_lab1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_microblaze_0_0 || ORIG_REF_NAME==mb_lab1_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_axi_uartlite_0_0/mb_lab1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_axi_uartlite_0_0 || ORIG_REF_NAME==mb_lab1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_dlmb_v10_0/mb_lab1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_dlmb_v10_0 || ORIG_REF_NAME==mb_lab1_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_ilmb_v10_0/mb_lab1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_ilmb_v10_0 || ORIG_REF_NAME==mb_lab1_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_dlmb_bram_if_cntlr_0/mb_lab1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_lab1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_ilmb_bram_if_cntlr_0/mb_lab1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_lab1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_lmb_bram_0/mb_lab1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_lmb_bram_0 || ORIG_REF_NAME==mb_lab1_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_xbar_0/mb_lab1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_xbar_0 || ORIG_REF_NAME==mb_lab1_xbar_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_microblaze_0_axi_periph_0/mb_lab1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_lab1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_microblaze_0_axi_intc_0/mb_lab1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_lab1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_microblaze_0_xlconcat_0/mb_lab1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_lab1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_mdm_1_0/mb_lab1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_mdm_1_0 || ORIG_REF_NAME==mb_lab1_mdm_1_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_clk_wiz_1_0/mb_lab1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_clk_wiz_1_0 || ORIG_REF_NAME==mb_lab1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_rst_clk_wiz_1_100M_0/mb_lab1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_lab1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_axi_gpio_0_0/mb_lab1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_axi_gpio_0_0 || ORIG_REF_NAME==mb_lab1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_axi_gpio_1_0/mb_lab1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_axi_gpio_1_0 || ORIG_REF_NAME==mb_lab1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_axi_gpio_2_0/mb_lab1_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_axi_gpio_2_0 || ORIG_REF_NAME==mb_lab1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_xlslice_0_0/mb_lab1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_xlslice_0_0 || ORIG_REF_NAME==mb_lab1_xlslice_0_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_xlslice_1_0/mb_lab1_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_xlslice_1_0 || ORIG_REF_NAME==mb_lab1_xlslice_1_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_xlconcat_0_0/mb_lab1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_xlconcat_0_0 || ORIG_REF_NAME==mb_lab1_xlconcat_0_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_axi_gpio_3_0/mb_lab1_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_axi_gpio_3_0 || ORIG_REF_NAME==mb_lab1_axi_gpio_3_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_alarm_timer_0_0/mb_lab1_alarm_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_alarm_timer_0_0 || ORIG_REF_NAME==mb_lab1_alarm_timer_0_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_xlslice_2_0/mb_lab1_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_xlslice_2_0 || ORIG_REF_NAME==mb_lab1_xlslice_2_0} -quiet] -quiet

# IP: bd/mb_lab1/ip/mb_lab1_test_ports_0_1/mb_lab1_test_ports_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab1_test_ports_0_1 || ORIG_REF_NAME==mb_lab1_test_ports_0_1} -quiet] -quiet

# XDC: D:/EECE387/lab8/lab8.gen/sources_1/bd/mb_lab1/mb_lab1_ooc.xdc
